import { Outfit } from 'next/font/google'
import './globals.css'

import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { ThemeProvider } from '@/components/ThemeProvider'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Callie Wong Music Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Include your head content, such as metadata and stylesheets */}
        <title>{metadata.title}</title>
        {/* Additional head elements go here */}
      </head>
      <body className={outfit.className}>
        <ThemeProvider attribute="class">
          <Header />
          <main>
            {/* Main content */}
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
